### ISSUE TITLE
Unable to fetch jobs list

### ISSUE THREAD

**Issue by zacatac** [merge-api/merge-ats-node#9]
Hi Merge Team, 

I was testing out the node client for your ATS API and I ran into an issue with the `GET: /jobs` endpoint. Seems like there are some undefined fields for this API.

Api version ` "@mergeapi/merge_ats_api": "^1.0.7",`

Code
```
const MergeAtsApi = require('@mergeapi/merge_ats_api')
  // specific to individual organizations
  const accountToken = '<TOKEN>';
  const opts = {}

  let client = MergeAtsApi.ApiClient.instance
  client.authentications['tokenAuth'] = {type: "bearer", accessToken: process.env.MERGE_API_KEY}
  const api = new MergeAtsApi.JobsApi()

  api.jobsList(accountToken, opts, (error, data) => {
    if (error) {
      console.log(error)
      res.status(400).json({ error })
    } else {
      res.status(200).json({ data })
    }
  });
```

Error 
```
ReferenceError: Office is not defined
    at Function.constructFromObject (/Users/zack/app/node_modules/@mergeapi/merge_ats_api/dist/model/Job.js:105:68)
    at Function.convertToType (/Users/zack/app/node_modules/@mergeapi/merge_ats_api/dist/ApiClient.js:667:25)
    at /Users/zack/app/node_modules/@mergeapi/merge_ats_api/dist/ApiClient.js:672:32
    at Array.map (<anonymous>)
    at Function.convertToType (/Users/zack/app/node_modules/@mergeapi/merge_ats_api/dist/ApiClient.js:671:25)
    at Function.constructFromObject (/Users/zack/app/node_modules/@mergeapi/merge_ats_api/dist/model/PaginatedJobList.js:68:50)
    at Function.convertToType (/Users/zack/app/node_modules/@mergeapi/merge_ats_api/dist/ApiClient.js:667:25)
    at ApiClient.deserialize (/Users/zack/app/node_modules/@mergeapi/merge_ats_api/dist/ApiClient.js:405:24)
    at /Users/zack/app/node_modules/@mergeapi/merge_ats_api/dist/ApiClient.js:533:29
    at Request.callback (/Users/zack/app/node_modules/superagent/lib/node/index.js:894:12)
    at /Users/zack/app/node_modules/superagent/lib/node/index.js:1126:20
    at IncomingMessage.<anonymous> (/Users/zack/app/node_modules/superagent/lib/node/parsers/json.js:22:7)
    at Stream.emit (node:events:394:28)
    at Stream.emit (node:domain:532:15)
    at Unzip.<anonymous> (/Users/zack/app/node_modules/superagent/lib/node/unzip.js:53:12)
    at Unzip.emit (node:events:394:28)
```

**Comment by zacatac** [comment]
Ah, looks like this was for the Javascript API which I can't seem to find the Github repo for.
